version: "3.8"

services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "7000:7000"  # Exposes port 7000
    environment:
      - MONGO_URL=mongodb+srv://syedakousar222:youjv72XqW9Inn8n@amreen.j1fof.mongodb.net/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine  # Official Redis image
    container_name: redis
    ports:
      - "6379:6379"  # Exposes Redis port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
